### PR TITLE
cdh repo priority in debian

### PR DESCRIPTION
**Pull request by TD-4242**
I was having an issue where the ubuntu universe package of zookeeper was overriding the cdh one and they are not compatible packages.  We use some packages of out universe for logging so I had to leave that enabled.  This sets the cloudera repository as higher priority.

This should probably be done for other distributions as well.

### CODE REVIEW

**Comment by wolf31o2** [comment]
This should be using the `apt_preference` LWRP from the `apt` cookbook and be applied to the other distributions, as well.

**Comment by TD-4242** [comment]
ahh i didn't even check to see if it was already in the apt cookbook.

**Comment by TD-4242** [comment]
I haven't tested this yet so only merge if you get a chance to test.

**Comment by wolf31o2** [comment]
Judging from the code, this looks like it'll work. I'll have to test it once I manage to settle down my local checkout... HDP 2.2 support is killing me.

**Comment by TD-4242** [comment]
I did finally get to test it and found the typo's  it was functional for me.

**Comment by wolf31o2** [comment]
Cool. Could you also do this same thing for the HDP and BigTop repos? I'll test them, but it would make this immediately mergeable, without a second PR to do the others. I really appreciate the contributions!

**Comment by TD-4242** [comment]
yes, I'll be out for the weekend but I can update it early next week.

**Comment by wolf31o2** [comment]
OK. If I get a chance to work on it before then, I'll post on here.

**Comment by wolf31o2** [comment]
Got a chance to work on it, so it's in #198 :smile:

**Pull request merged**
