### PR TITLE
Refactor oozie download url from sencha (broken) to cloudera

### PR DESCRIPTION
**Pull request by jeremyhahn**

### CODE REVIEW

**Comment by wolf31o2** [comment]
Can you resend this without the metadata changes? We do version bumps in their own pulls, along with the CHANGELOG.md updates.

**Comment by wolf31o2** [comment]
Also, I am trying to fix the test failures in #266 so probably best to wait for that to be merged before rebasing off `master` or anything.

**Comment by wolf31o2** [comment]
Thanks for the submission!

**Comment by jeremyhahn** [comment]
:+1:

**Pull request merged**
