### PR TITLE
change spark-defaults from XML to .conf property file

### PR DESCRIPTION
**Pull request by antonymayi**
The spark-defaults config is supposed to be a spark-defaults.conf property file, not a XML as in the original recipe.

### CODE REVIEW

**Comment by wolf31o2** [comment]
You must also update the tests under spec.

**Comment by antonymayi** [comment]
is it better now?

**Comment by wolf31o2** [comment]
Excellent. LGTM but I need a quick approval since this is your first contribution to a Cask-managed project.

@nitinmotgi can I get a :+1:

**Comment by nitinmotgi** [comment]
LGTM 👍

**Pull request merged**
