### PR TITLE
add hdp 2.6.1

### PR DESCRIPTION
**Pull request by dereklwood**
support for HDP 2.6.1.0

### CODE REVIEW

**Comment by dereklwood** [comment]
code climate is existing issue, and seems I dont have authorization to suppress

**Comment by mattwuenschel** [comment]
LGTM 👍

**Comment by wolf31o2** [comment]
Did you login to codeclimate using your GitHub id? Also, you could try adding the cookbook to your codeclimate and see if that does it. There's no granular permissions in codeclimate. It should allow anyone with write access to approve.

**Comment by wolf31o2** [comment]
Ooh... it may be because *I* setup the integration and no longer have write access. You may need to go to https://codeclimate.com/github/caskdata/hadoop_cookbook Settings tab, then Git Repository, and reinstall the webhook and integration.

**Comment by dereklwood** [comment]
Hmmm, the Settings tab doesn't show up for me anywhere... according to the codeclimate docs, their permissions are separate and not pulled from Github.  Is there maybe an organization setup that I was never part of (likely because I had no codeclimate account until now)?  From the Cask GH Org it just shows all green.

I also looked at setting it up via my new codeclimate account, but hesitated when it requires access to every Org i'm a member of :(

**Comment by wolf31o2** [comment]
I don't know, honestly. It asks for permission to every org, but it only uses them when setting up the links, AFAIK. It's fairly well trusted. I never did anything at an org level. I just added each repo that I cared about, individually.

**Pull request merged**
