### PR TITLE
Remove policy_rcd; should use dpkg_autostart cookbook, instead

### PR DESCRIPTION
**Pull request by wolf31o2**
This method is completely unused in this cookbook and the functionality is provided by the `dpkg_autostart` cookbook. Removing the function from our cookbook.

### CODE REVIEW

**Comment by dereklwood** [comment]
Unless i'm missing something, this helper is still used in some recipes, such as:  https://github.com/caskdata/hadoop_cookbook/blob/master/recipes/oozie.rb#L32

**Comment by wolf31o2** [comment]
Wow. I blanked that there were a couple that provided init scripts in their main package, versus having a secondary package with just an init script. You're right. Putting this on hold. I'll update tomorrow using `dpkg_autostart` cookbook's LWRP.

**Comment by wolf31o2** [comment]
Updated to use `dpkg_autostart` LWRP.

**Comment by mattwuenschel** [comment]
LGTM 👍

**Pull request merged**
