### PR TITLE
what looks like some minor typos

### PR DESCRIPTION
**Pull request by TD-4242**
the dev package at least on my ubuntu 14.04 box is libsnappy-dev without the '1'

also looks like the ha_checkconfig recipe may have been renamed.

### CODE REVIEW

**Comment by wolf31o2** [comment]
Good catch. I updated the snappy one in my current WIP branch, but I should have made it its own PR. Anyway, you can fix the test failure by also changing `spec/_compression_libs_spec.rb` to match your changes.

**Comment by wolf31o2** [comment]
Actually, if you rebase against master, you'll see that the library name change has been merged.

**Comment by wolf31o2** [comment]
That's just:
```
git fetch origin
git rebase origin/master
git push
```

**Comment by TD-4242** [comment]
cool I'll close this pull request then.

**Pull request closed without merging**
